#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# 台股回測系統：開始 #5（資料同步）前的帳號設定。
# 取得 FinMind API token 與 Supabase 資料庫連線字串，寫入 backend/.env，
# 並設為 GitHub Actions secrets（FINMIND_TOKEN、DATABASE_URL）。
#
# 用法：在 repo 任何位置執行 scripts/setup-accounts.sh
# 需要：bash、curl；設定 GitHub secrets 需要已登入的 gh（gh auth login）。

cd "$(git -C "$(dirname "$0")" rev-parse --show-toplevel)"
ENV_FILE="backend/.env" # 已列在 .gitignore，不會被 commit

TOTAL_STAGES=6

banner "台股回測系統：FinMind 與 Supabase 帳號設定"

# ──────────────────────────────────────────────────────────────────────────
stage "FinMind：註冊並驗證信箱"
say "FinMind 是行情資料來源。先註冊帳號並驗證信箱，驗證後才拿得到 API token。"
open_url "https://finmindtrade.com/"
step "在 FinMind 網站上點「註冊」，用你的 email 建立帳號。"
step "到信箱點驗證信裡的連結，完成信箱驗證。"
note "如果網站上的按鈕名稱和這裡寫的不同，以網站為準。"
pause "完成註冊與信箱驗證後，按 Enter 繼續"

# ──────────────────────────────────────────────────────────────────────────
stage "FinMind：購買 Backer 方案（可先跳過）"
say "依 ADR 0003，正式上線使用 Backer 方案（月繳 NT\$699／年繳 NT\$5,499）："
note "每小時 1,600 次請求（免費版 600 次）；只限非商業用途。"
note "付款是單次付款、不會自動續約，到期後自動回到免費版。"
say "開發初期可以先用免費版，等要回補全部歷史資料或上線前再購買。"
open_url "https://finmind.github.io/Pricing/"
if confirm "現在要購買 Backer 方案嗎？（會進行付款）"; then
  step "依 Pricing 頁面的說明完成 Backer 方案的付款。"
  pause "付款完成後，按 Enter 繼續"
else
  note "先跳過；之後再從 https://finmind.github.io/Pricing/ 購買即可，不必重跑這個腳本。"
  pause "按 Enter 繼續"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "FinMind：取得 API token"
say "回測系統用這個 token 呼叫 FinMind API。"
open_url "https://finmindtrade.com/"
step "登入 FinMind，進入會員或使用者資訊頁面，找到 API token 並複製。"
note "如果找不到，可以查 FinMind 文件：https://finmind.github.io/quickstart/"
ask_secret FINMIND_TOKEN "貼上 FinMind API token（輸入不會顯示）："
if [[ -z "$FINMIND_TOKEN" ]]; then
  warn "沒有輸入 token，請重新執行這個腳本。"; exit 1
fi
write_env FINMIND_TOKEN "$FINMIND_TOKEN"
say "測試 token 是否有效…"
if curl -fsS -G "https://api.finmindtrade.com/api/v4/data" \
     -H "Authorization: Bearer $FINMIND_TOKEN" \
     --data-urlencode "dataset=TaiwanStockInfo" -o /dev/null 2>/dev/null; then
  printf '  %s✓ FinMind token 可以使用%s\n' "$GREEN" "$RESET"
else
  warn "測試請求失敗。可能是 token 有誤、網路問題，或 FinMind 正在維護（每週日 00:00–03:00）。"
  note "token 已經存好；之後確認沒問題再繼續即可。"
fi
pause "按 Enter 繼續"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase：建立專案"
say "Supabase 提供 PostgreSQL 資料庫與 Google 登入（ADR 0004）。"
open_url "https://supabase.com/dashboard/projects"
step "登入或註冊 Supabase，點「New project」。"
step "Name 可填 stock-risk-tool；Region 建議選離台灣近的 Tokyo 或 Singapore。"
step "設定 Database Password，並把它存進你的密碼管理工具，下一步會用到。"
step "按下建立，等專案初始化完成（約一兩分鐘）。"
warn "這個資料庫密碼本腳本不會保存，請自己記好。"
pause "專案建立完成後，按 Enter 繼續"

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase：取得資料庫連線字串"
say "回測系統與每日同步（GitHub Actions）都用這個連線字串連到資料庫。"
open_url "https://supabase.com/dashboard/projects"
step "進入剛建立的專案，點頁面上方的「Connect」。"
step "在連線方式中選「Session pooler」，複製 URI（開頭是 postgresql://）。"
note "請用 Session pooler：Direct connection 只支援 IPv6，GitHub Actions 可能連不上。"
step "把 URI 裡的 [YOUR-PASSWORD] 換成上一步設定的資料庫密碼。"
ask_secret DATABASE_URL "貼上完整的連線字串（輸入不會顯示）："
if [[ "$DATABASE_URL" != postgres* ]]; then
  warn "連線字串應該以 postgresql:// 開頭，請重新執行這個腳本。"; exit 1
fi
if [[ "$DATABASE_URL" == *"[YOUR-PASSWORD]"* ]]; then
  warn "連線字串裡還有 [YOUR-PASSWORD]，請換成真正的密碼後重新執行。"; exit 1
fi
write_env DATABASE_URL "$DATABASE_URL"
if command -v psql >/dev/null 2>&1; then
  say "測試資料庫連線…"
  if psql "$DATABASE_URL" -c 'select 1' >/dev/null 2>&1; then
    printf '  %s✓ 資料庫可以連線%s\n' "$GREEN" "$RESET"
  else
    warn "連線失敗。請確認密碼是否正確、是否選了 Session pooler。"
  fi
else
  note "沒有安裝 psql，略過連線測試。"
fi
pause "按 Enter 繼續"

# ──────────────────────────────────────────────────────────────────────────
stage "GitHub：設定 Actions secrets"
say "每日資料同步在 GitHub Actions 上執行，需要這兩個值："
note "FINMIND_TOKEN、DATABASE_URL → hswenforwork/Stock-Risk-Tool 的 Actions secrets"
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "找不到已登入的 gh。可以先執行 gh auth login，或在下列頁面手動新增："
  note "https://github.com/hswenforwork/Stock-Risk-Tool/settings/secrets/actions"
fi
if confirm "要把 FINMIND_TOKEN 與 DATABASE_URL 設為這個 repo 的 GitHub Actions secrets 嗎？"; then
  set_secret FINMIND_TOKEN "$FINMIND_TOKEN"
  set_secret DATABASE_URL "$DATABASE_URL"
else
  SKIPPED+=("GitHub secrets FINMIND_TOKEN、DATABASE_URL（gh secret set 或到 repo 設定頁面新增）")
fi
pause "按 Enter 看總結"

finish
say "完成後回到 Claude，告訴它帳號已經設定好，就可以開始做 #5（資料同步）。"
printf '\n'
